### PR TITLE
merge main into staging

### PR DESCRIPTION
**Pull request by nathen418**

### CODE REVIEW

**Comment by schiltz3** [comment]
Do we want to disable the docker workflow when merging from master into other branches?

**Comment by schiltz3** [comment]
I'll work on making a workflow that automatically merges master back into staging so that we don't have to keep doing this

**Comment by nathen418** [comment]
slay that's exactly what we need

**Comment by schiltz3** [comment]
actually we should never have to merge master back into staging as long as we never merge to master directly except though staging

**Comment by schiltz3** [comment]
master will always be behind staging

**Comment by nathen418** [comment]
that is my idea, however, on the off chance it happens, it would be kinda nice. also, I'm gonna work on contributing guidelines that will lay that out, as well as branch naming guidelines, issue/pr templates, etc

**Comment by schiltz3** [comment]
Sounds good. Github won't let me approve since main is behind staging

**Pull request merged**
